### ISSUE TITLE
Please release helix package at pypi

### ISSUE THREAD

**Issue by reece** [BenOckmore/helix#1]
Hi Ben- It looks like you were considering making a package called helix and registered it at pypi, but that the project is now defunct (per github commits). If you're not going to use the name, would you please release it at pypi? Thanks, Reece

https://pypi.python.org/pypi/Helix/

**Comment by BenOckmore** [comment]
Not a problem, I'll get round to it as soon as I can, hopefully this weekend. Out of interest, what's your new project?

**Comment by reece** [comment]
On Fri, Nov 18, 2016 at 4:54 PM, Ben Ockmore notifications@github.com
wrote:

> Not a problem, I'll get round to it as soon as I can, hopefully this
> weekend. Out of interest, what's your new project?
> 
> Great. Thanks!

It's a package to interact with data from helix.com, a DNA sequencing
company. The nascent package is here: https://github.com/reece/helixclient .

I don't work for them, but I fortunately do work for a company that's cool
with coding out in the open.

Cheers,
Reece

**Comment by BenOckmore** [comment]
All done - best of luck with your project!

**Comment by reece** [comment]
Fabulous. Thanks Ben!
